CREATE TABLE categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL,
    description TEXT,
    price       NUMERIC(12,2) NOT NULL,
    image_url   VARCHAR(1024),
    category_id BIGINT REFERENCES categories(id)
);

CREATE INDEX idx_products_name ON products (lower(name));

INSERT INTO categories (id, name) VALUES
    (1, 'Electronics'),
    (2, 'Books');

INSERT INTO products (id, name, description, price, image_url, category_id) VALUES
    (1, 'Flash Sale Headphones', 'Limited edition wireless headphones', 199.99, 'https://picsum.photos/seed/1/300', 1),
    (2, 'Mechanical Keyboard',   'Hot-swappable RGB keyboard',          349.00, 'https://picsum.photos/seed/2/300', 1),
    (3, 'Domain-Driven Design',  'Tackling complexity in software',      59.90, 'https://picsum.photos/seed/3/300', 2);

-- advance identity sequences past the seeded ids
SELECT setval(pg_get_serial_sequence('categories', 'id'), (SELECT MAX(id) FROM categories));
SELECT setval(pg_get_serial_sequence('products', 'id'), (SELECT MAX(id) FROM products));
